#!/bin/sh
# Launch bubblewrapped Discord from package https://aur.archlinux.org/packages/discord_arch_electron/

XDG_CACHE_HOME=${XDG_CACHE_HOME:-"$HOME/.cache"}

exec bwrap \
--unshare-all \
--share-net \
--clearenv \
--setenv HOME $HOME \
--setenv WAYLAND_DISPLAY $WAYLAND_DISPLAY \
--setenv XDG_RUNTIME_DIR $XDG_RUNTIME_DIR \
--setenv DBUS_SESSION_BUS_ADDRESS $DBUS_SESSION_BUS_ADDRESS \
--setenv DISPLAY $DISPLAY \
--new-session \
--ro-bind /lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2 \
--ro-bind /bin/sh /bin/sh \
--ro-bind /usr/bin/discord /usr/bin/discord \
--ro-bind /usr/bin/electron /usr/bin/electron \
--ro-bind /usr/bin/bash /usr/bin/bash \
--ro-bind /usr/lib /usr/lib \
--ro-bind /usr/share /usr/share \
--ro-bind /sys/devices /sys/devices \
--ro-bind /sys/dev/char /sys/dev/char \
--proc /proc \
--dev /dev \
--dev-bind /dev/dri /dev/dri \
--bind /tmp /tmp \
--ro-bind /run/systemd/resolve /run/systemd/resolve \
--ro-bind "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY" "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY" \
--ro-bind "$XDG_RUNTIME_DIR/pulse" "$XDG_RUNTIME_DIR/pulse" \
--ro-bind "$XDG_RUNTIME_DIR/bus" "$XDG_RUNTIME_DIR/bus" \
--ro-bind /run/dbus/system_bus_socket /run/dbus/system_bus_socket \
--bind /run/user/$UID/dconf/user /run/user/$UID/dconf/user \
--bind ~/Applications/Discord/.config/discord ~/.config/discord \
--ro-bind ~/.config/electron-flags.conf ~/.config/electron-flags.conf \
--ro-bind ~/.icons/default/index.theme ~/.icons/default/index.theme \
--bind "$XDG_CACHE_HOME/mesa_shader_cache" "$HOME/.cache/mesa_shader_cache" \
--bind "$XDG_CACHE_HOME/fontconfig" "$HOME/.cache/fontconfig" \
--tmpfs ~/.config/chromium \
--tmpfs ~/.config/pulse \
--ro-bind /etc /etc \
--bind ~/Shared ~/Shared \
/usr/bin/discord
