#!/bin/sh
# Script to launch bubblewrapped discord (from package https://aur.archlinux.org/packages/discord_arch_electron/)

exec bwrap \
--unshare-all \
--share-net \
--new-session \
--ro-bind /lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2 \
--ro-bind /bin/sh /bin/sh \
--ro-bind /usr/bin/discord /usr/bin/discord \
--ro-bind /usr/bin/electron /usr/bin/electron \
--ro-bind /usr/bin/bash /usr/bin/bash \
--ro-bind /usr/lib /usr/lib \
--ro-bind /usr/share /usr/share \
--ro-bind /sys/devices /sys/devices \
--ro-bind /sys/dev/char /sys/dev/char \
--proc /proc \
--dev /dev \
--dev-bind /dev/dri /dev/dri \
--bind /tmp /tmp \
--ro-bind /run/systemd/resolve /run/systemd/resolve \
--ro-bind /run/user/$UID/wayland-1 /run/user/$UID/wayland-1 \
--ro-bind /run/user/$UID/pulse /run/user/$UID/pulse \
--ro-bind /run/user/$UID/bus /run/user/$UID/bus \
--ro-bind /run/dbus/system_bus_socket /run/dbus/system_bus_socket \
--bind /run/user/$UID/dconf/user /run/user/$UID/dconf/user \
--bind ~/Applications/Discord ~/ \
--ro-bind ~/.config/electron-flags.conf ~/.config/electron-flags.conf \
--ro-bind ~/.icons/default/index.theme ~/.icons/default/index.theme \
--tmpfs ~/.cache \
--tmpfs ~/.config/chromium \
--tmpfs ~/.config/pulse \
--tmpfs ~/.config/discord/Cache \
--tmpfs ~/.config/discord/Code\ Cache \
--ro-bind /etc /etc \
/usr/bin/discord
