#!/bin/sh

XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-"$HOME/.config"}
XDG_DATA_HOME=${XDG_DATA_HOME:-"$HOME/.local/share"}

exec bwrap \
--unshare-all \
--clearenv \
--setenv HOME $HOME \
--setenv WAYLAND_DISPLAY $WAYLAND_DISPLAY \
--setenv XDG_RUNTIME_DIR $XDG_RUNTIME_DIR \
--new-session \
--ro-bind /usr/bin/gnome-font-viewer /usr/bin/gnome-font-viewer \
--ro-bind /usr/lib /usr/lib \
--ro-bind /lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2 \
--ro-bind /run/user/$UID/$WAYLAND_DISPLAY /run/user/$UID/$WAYLAND_DISPLAY \
--ro-bind /usr/share/X11/xkb /usr/share/X11/xkb \
--ro-bind /usr/share/icons /usr/share/icons \
--ro-bind /usr/share/mime /usr/share/mime \
--ro-bind /usr/share/fonts /usr/share/fonts \
--ro-bind /usr/share/locale /usr/share/locale \
--ro-bind /usr/share/glib-2.0 /usr/share/glib-2.0 \
--ro-bind /usr/share/themes /usr/share/themes \
--ro-bind /etc/fonts /etc/fonts \
--ro-bind $XDG_CONFIG_HOME/dconf/user ~/.config/dconf/user \
--ro-bind $XDG_DATA_HOME/fonts ~/.local/share/fonts \
--bind ~/.cache/thumbnails ~/.cache/thumbnails \
/usr/bin/gnome-font-viewer
